ALTER TABLE public.restaurants
  ADD COLUMN IF NOT EXISTS delivery_fee_0_10 NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_fee_10_15 NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_fee_15_20 NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_fee_20_30 NUMERIC(10,2) NOT NULL DEFAULT 0;

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS delivery_amount NUMERIC(10,2) NOT NULL DEFAULT 0;

UPDATE public.orders
SET delivery_amount = COALESCE(delivery_amount, 0)
WHERE delivery_amount IS NULL;
